### ISSUE TITLE
What are you using the tunnel for?

### ISSUE THREAD

**Issue by ovizii** [JenswBE/flash#1]
Hi Jens,

may I ask how you are using the "SSH tunnel for Guacd"? I am not knowledgeable enough to figure it out from your docker-compose file.

Thanks.

**Comment by JenswBE** [comment]
Hi ovizii,

My apologies for the late reply. Seems notifications weren't turned on for this repo.

To give you some context, at home I have 2 computers. One is Flash, a Raspberry Pi which I use as a gateway host. This one is always running. The second one is Hercules, which is my main desktop. This one is switched off by default. Next to this, the Guacamole front-end is running on a remote VPS called Pumba (used to be Wolverine, but I moved it today).

To limit the attack surface for my home, I decided to make only the Pi available to the internet. In case I want to access another device, it will always be through the Pi. Next to this, I also use the Pi to send WOL packets to my main desktop.

To be able to access my desktop, I installed Guacd on the Pi. As this service is not secured, it's only exposed to localhost. Next, I run a SSH tunnel from the remote VPS towards this Pi. The container connects to the Guacd on localhost and exposes the service to the front-end of Guacamole.

You can find more info in [Pumba's docker-compose.yml](https://github.com/JenswBE/pumba/blob/master/docker-compose.yml#L155) as of line 155 and on line 107.

Finally, you can connect to the remote Guacd using following options:
![guacamole](https://user-images.githubusercontent.com/6514515/63227797-bf72f180-c1ea-11e9-8584-7198dc67b914.png)

For the hostname of the target, you should use the internal ip of your home network.

Hopefully, above explanation might be useful to you.
Please feel free to ask additional details if required!

Kind regards,
Jens

**Comment by ovizii** [comment]
Thanks for the detailed explanation, I now see the purpose of the flash tunnel.
